services:
  mlbserver:
    image: tonywagner/mlbserver:latest
    container_name: mlbserver
    environment:
      - TZ=America/New York
      - data_directory=/mlbserver/data_directory
      - account_username=your.account.email@example.com
      - account_password=youraccountpassword
      #- fav_teams=AZ,BAL
      #- debug=false
      #- port=9999
      #- multiview_port=10000
      #- multiview_path=
      #- ffmpeg_path=
      #- ffmpeg_encoder=
      #- page_username=
      #- page_password=
      #- content_protect=
      #- gamechanger_delay=0
    ports:
      - 9999:9999
      - 10000:10000
    volumes:
      - /path/to/your/desired/local/mlbserver/persistent/data/directory:/mlbserver/data_directory